development:
  secret_token:           33c7d0c42157adf91b2d0eec0c0331899f68939bc95dc67dc899f343e757b3a2be317e10cb35ab9c45ba45c512f2732bd5bbce4c030281bddb93a100df80809c
  secret_key_base:        6ff1bea8b001ed1050a7a346ed0200978869f7890823b07d60c4147b03fb9330ae9585b5e844b3ad8b2fd967b5c121384793f360c1e685dba6c50e399b010dc7
  devise_secret_key:      2c6914e48e5dcfcc10757bc22798414d2f49cd10349f131ca0e3b90c4e587e21eb4487f5aba7328d2647c23edce3379c38b18f929c7c4b5b171c500940bc7e6e

  twitter_key:            LP4QG8LkNsYM4GVURGyxIPogF
  twitter_secret:         lF3JO4Ed2fBnvtInvyX48Atgt25M7MdAbWcyYZMkLb6txPGrJN

  facebook_app_id:        1249766918390462
  facebook_app_secret:    c39738bf69dbd6bb9205326933556e77

  github_client_id:       16f96b58b2b320779fdb
  github_client_secret:   15ffdecccec174336ab1d81931b8a29911d5deb7

production:
  secret_token:           <%= ENV['SECRET_TOKEN'] %>
  secret_key_base:        <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key:      <%= ENV['DEVISE_SECRET_KEY'] %>

  twitter_key:            <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_secret:         <%= ENV['TWITTER_CONSUMER_SECRET'] %>

  facebook_app_id:        <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret:    <%= ENV['FACEBOOK_APP_SECRET'] %>

  github_client_id:       <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret:   <%= ENV['GITHUB_CLIENT_SECRET'] %>
