production:
  secret_token:           <%= ENV['SECRET_TOKEN'] %>
  secret_key_base:        <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key:      <%= ENV['DEVISE_SECRET_KEY'] %>

  twitter_key:            <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_secret:         <%= ENV['TWITTER_CONSUMER_SECRET'] %>

  facebook_app_id:        <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret:    <%= ENV['FACEBOOK_APP_SECRET'] %>

  github_client_id:       <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret:   <%= ENV['GITHUB_CLIENT_SECRET'] %>
